/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms;

import subsystems.individuos.autorizado;

/**
 *
 * @author Uzer
 */
public class informacionAutorizado extends javax.swing.JDialog {

    /**
     * Creates new form informacionAutorizado
     */
    public informacionAutorizado(java.awt.Frame parent, boolean modal, autorizado autorizado) {
        super(parent, modal);
        initComponents();
        
        for (java.awt.Component cp : this.getComponents()){
            cp.setEnabled(false);
        }
        
        text_apellidos_padre4.setText(autorizado.getApellidos());
        text_nombres_padre4.setText(autorizado.getNombres());
        text_ocupacion_padre4.setText(autorizado.getParentesco());
        text_ci_padre4.setText(String.valueOf(autorizado.getCi()));
        text_tlf_padre8.setText(autorizado.getTlf1());
        text_tlf_padre9.setText(autorizado.getTlf2());
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        dat_padre4 = new javax.swing.JPanel();
        label_apellido_padre4 = new javax.swing.JLabel();
        text_apellidos_padre4 = new javax.swing.JTextField();
        label_nombes_padre4 = new javax.swing.JLabel();
        text_nombres_padre4 = new javax.swing.JTextField();
        label_ci_padre4 = new javax.swing.JLabel();
        text_ci_padre4 = new javax.swing.JTextField();
        label_ocupacion_padre4 = new javax.swing.JLabel();
        text_ocupacion_padre4 = new javax.swing.JTextField();
        label_tlf_padre8 = new javax.swing.JLabel();
        text_tlf_padre8 = new javax.swing.JTextField();
        label_tlf_padre9 = new javax.swing.JLabel();
        text_tlf_padre9 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(27, 120, 101));
        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 32));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(250, 247, 239));
        jLabel4.setText("AUTORIZADO PARA EL RETIRO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(jLabel4)
                .addContainerGap(216, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dat_padre4.setBackground(new java.awt.Color(222, 255, 222));
        dat_padre4.setPreferredSize(new java.awt.Dimension(600, 450));

        label_apellido_padre4.setText("Apellidos");

        text_apellidos_padre4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_apellidos_padre4ActionPerformed(evt);
            }
        });

        label_nombes_padre4.setText("Nombres");

        text_nombres_padre4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_nombres_padre4ActionPerformed(evt);
            }
        });

        label_ci_padre4.setText("C.I");

        label_ocupacion_padre4.setText("Parentesco");

        label_tlf_padre8.setText("TELF 1");

        text_tlf_padre8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_tlf_padre8ActionPerformed(evt);
            }
        });

        label_tlf_padre9.setText("TELF 2");
        label_tlf_padre9.setToolTipText("");

        text_tlf_padre9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_tlf_padre9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dat_padre4Layout = new javax.swing.GroupLayout(dat_padre4);
        dat_padre4.setLayout(dat_padre4Layout);
        dat_padre4Layout.setHorizontalGroup(
            dat_padre4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dat_padre4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dat_padre4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dat_padre4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(dat_padre4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_nombes_padre4)
                            .addComponent(label_apellido_padre4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dat_padre4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(text_nombres_padre4, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                            .addComponent(text_apellidos_padre4)))
                    .addGroup(dat_padre4Layout.createSequentialGroup()
                        .addComponent(label_ocupacion_padre4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_ocupacion_padre4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dat_padre4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_tlf_padre8)
                    .addComponent(label_tlf_padre9)
                    .addComponent(label_ci_padre4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dat_padre4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text_ci_padre4, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dat_padre4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(text_tlf_padre9, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                        .addComponent(text_tlf_padre8)))
                .addGap(69, 69, 69))
        );
        dat_padre4Layout.setVerticalGroup(
            dat_padre4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dat_padre4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dat_padre4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_ci_padre4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_ci_padre4)
                    .addComponent(text_apellidos_padre4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_apellido_padre4))
                .addGap(3, 3, 3)
                .addGroup(dat_padre4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dat_padre4Layout.createSequentialGroup()
                        .addGroup(dat_padre4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_nombes_padre4)
                            .addComponent(text_nombres_padre4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_tlf_padre8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dat_padre4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_ocupacion_padre4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_ocupacion_padre4)
                            .addComponent(label_tlf_padre9)))
                    .addGroup(dat_padre4Layout.createSequentialGroup()
                        .addComponent(text_tlf_padre8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_tlf_padre9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dat_padre4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dat_padre4, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_apellidos_padre4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_apellidos_padre4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_apellidos_padre4ActionPerformed

    private void text_nombres_padre4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_nombres_padre4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_nombres_padre4ActionPerformed

    private void text_tlf_padre8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_tlf_padre8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_tlf_padre8ActionPerformed

    private void text_tlf_padre9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_tlf_padre9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_tlf_padre9ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chec_bachiller_padre;
    private javax.swing.JCheckBox chec_bachiller_padre1;
    private javax.swing.JCheckBox chec_bachiller_padre2;
    private javax.swing.JCheckBox chec_bachiller_padre3;
    private javax.swing.JCheckBox check_c_padre;
    private javax.swing.JCheckBox check_c_padre1;
    private javax.swing.JCheckBox check_c_padre2;
    private javax.swing.JCheckBox check_c_padre3;
    private javax.swing.JCheckBox check_d_padre;
    private javax.swing.JCheckBox check_d_padre1;
    private javax.swing.JCheckBox check_d_padre2;
    private javax.swing.JCheckBox check_d_padre3;
    private javax.swing.JCheckBox check_ext_padre;
    private javax.swing.JCheckBox check_ext_padre1;
    private javax.swing.JCheckBox check_ext_padre2;
    private javax.swing.JCheckBox check_ext_padre3;
    private javax.swing.JCheckBox check_no_bachiller_padre;
    private javax.swing.JCheckBox check_no_bachiller_padre1;
    private javax.swing.JCheckBox check_no_bachiller_padre2;
    private javax.swing.JCheckBox check_no_bachiller_padre3;
    private javax.swing.JCheckBox check_s_padre;
    private javax.swing.JCheckBox check_s_padre1;
    private javax.swing.JCheckBox check_s_padre2;
    private javax.swing.JCheckBox check_s_padre3;
    private javax.swing.JCheckBox check_superior_padre;
    private javax.swing.JCheckBox check_superior_padre1;
    private javax.swing.JCheckBox check_superior_padre2;
    private javax.swing.JCheckBox check_superior_padre3;
    private javax.swing.JCheckBox check_tsu_padre;
    private javax.swing.JCheckBox check_tsu_padre1;
    private javax.swing.JCheckBox check_tsu_padre2;
    private javax.swing.JCheckBox check_tsu_padre3;
    private javax.swing.JCheckBox check_v_padre;
    private javax.swing.JCheckBox check_v_padre1;
    private javax.swing.JCheckBox check_v_padre2;
    private javax.swing.JCheckBox check_v_padre3;
    private javax.swing.JCheckBox check_ven_padre;
    private javax.swing.JCheckBox check_ven_padre1;
    private javax.swing.JCheckBox check_ven_padre2;
    private javax.swing.JCheckBox check_ven_padre3;
    private javax.swing.JPanel dat_padre;
    private javax.swing.JPanel dat_padre1;
    private javax.swing.JPanel dat_padre2;
    private javax.swing.JPanel dat_padre3;
    private javax.swing.JPanel dat_padre4;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label_apellido_padre;
    private javax.swing.JLabel label_apellido_padre1;
    private javax.swing.JLabel label_apellido_padre2;
    private javax.swing.JLabel label_apellido_padre3;
    private javax.swing.JLabel label_apellido_padre4;
    private javax.swing.JLabel label_ci_padre;
    private javax.swing.JLabel label_ci_padre1;
    private javax.swing.JLabel label_ci_padre2;
    private javax.swing.JLabel label_ci_padre3;
    private javax.swing.JLabel label_ci_padre4;
    private javax.swing.JLabel label_correo_padre;
    private javax.swing.JLabel label_correo_padre1;
    private javax.swing.JLabel label_correo_padre2;
    private javax.swing.JLabel label_correo_padre3;
    private javax.swing.JLabel label_direc_hab_padre;
    private javax.swing.JLabel label_direc_hab_padre1;
    private javax.swing.JLabel label_direc_hab_padre2;
    private javax.swing.JLabel label_direc_hab_padre3;
    private javax.swing.JLabel label_direc_trabaj_padre;
    private javax.swing.JLabel label_direc_trabaj_padre1;
    private javax.swing.JLabel label_direc_trabaj_padre2;
    private javax.swing.JLabel label_direc_trabaj_padre3;
    private javax.swing.JLabel label_edad_padre;
    private javax.swing.JLabel label_edad_padre1;
    private javax.swing.JLabel label_edad_padre2;
    private javax.swing.JLabel label_edad_padre3;
    private javax.swing.JLabel label_estadociv_padre;
    private javax.swing.JLabel label_estadociv_padre1;
    private javax.swing.JLabel label_estadociv_padre2;
    private javax.swing.JLabel label_estadociv_padre3;
    private javax.swing.JLabel label_fec_nac_padre;
    private javax.swing.JLabel label_fec_nac_padre1;
    private javax.swing.JLabel label_fec_nac_padre2;
    private javax.swing.JLabel label_fec_nac_padre3;
    private javax.swing.JLabel label_grado_padre;
    private javax.swing.JLabel label_grado_padre1;
    private javax.swing.JLabel label_grado_padre2;
    private javax.swing.JLabel label_grado_padre3;
    private javax.swing.JLabel label_lugar_nac_padre;
    private javax.swing.JLabel label_lugar_nac_padre1;
    private javax.swing.JLabel label_lugar_nac_padre2;
    private javax.swing.JLabel label_lugar_nac_padre3;
    private javax.swing.JLabel label_lugar_nac_padre4;
    private javax.swing.JLabel label_lugar_nac_padre5;
    private javax.swing.JLabel label_lugar_nac_padre6;
    private javax.swing.JLabel label_lugar_nac_padre7;
    private javax.swing.JLabel label_nacionalidad_padre;
    private javax.swing.JLabel label_nacionalidad_padre1;
    private javax.swing.JLabel label_nacionalidad_padre2;
    private javax.swing.JLabel label_nacionalidad_padre3;
    private javax.swing.JLabel label_nombes_padre;
    private javax.swing.JLabel label_nombes_padre1;
    private javax.swing.JLabel label_nombes_padre2;
    private javax.swing.JLabel label_nombes_padre3;
    private javax.swing.JLabel label_nombes_padre4;
    private javax.swing.JLabel label_ocupacion_padre;
    private javax.swing.JLabel label_ocupacion_padre1;
    private javax.swing.JLabel label_ocupacion_padre2;
    private javax.swing.JLabel label_ocupacion_padre3;
    private javax.swing.JLabel label_ocupacion_padre4;
    private javax.swing.JLabel label_tlf_padre;
    private javax.swing.JLabel label_tlf_padre1;
    private javax.swing.JLabel label_tlf_padre2;
    private javax.swing.JLabel label_tlf_padre3;
    private javax.swing.JLabel label_tlf_padre4;
    private javax.swing.JLabel label_tlf_padre5;
    private javax.swing.JLabel label_tlf_padre6;
    private javax.swing.JLabel label_tlf_padre7;
    private javax.swing.JLabel label_tlf_padre8;
    private javax.swing.JLabel label_tlf_padre9;
    private javax.swing.JTextField text_apellidos_padre;
    private javax.swing.JTextField text_apellidos_padre1;
    private javax.swing.JTextField text_apellidos_padre2;
    private javax.swing.JTextField text_apellidos_padre3;
    private javax.swing.JTextField text_apellidos_padre4;
    private javax.swing.JTextField text_ci_padre;
    private javax.swing.JTextField text_ci_padre1;
    private javax.swing.JTextField text_ci_padre2;
    private javax.swing.JTextField text_ci_padre3;
    private javax.swing.JTextField text_ci_padre4;
    private javax.swing.JTextField text_correo_padre;
    private javax.swing.JTextField text_correo_padre1;
    private javax.swing.JTextField text_correo_padre2;
    private javax.swing.JTextField text_correo_padre3;
    private javax.swing.JTextField text_direc_hab_padre;
    private javax.swing.JTextField text_direc_hab_padre1;
    private javax.swing.JTextField text_direc_hab_padre2;
    private javax.swing.JTextField text_direc_hab_padre3;
    private javax.swing.JTextField text_direc_trabj_padre;
    private javax.swing.JTextField text_direc_trabj_padre1;
    private javax.swing.JTextField text_direc_trabj_padre2;
    private javax.swing.JTextField text_direc_trabj_padre3;
    private javax.swing.JTextField text_edad_padre;
    private javax.swing.JTextField text_edad_padre1;
    private javax.swing.JTextField text_edad_padre2;
    private javax.swing.JTextField text_edad_padre3;
    private javax.swing.JTextField text_fec_nac_padre;
    private javax.swing.JTextField text_fec_nac_padre1;
    private javax.swing.JTextField text_fec_nac_padre2;
    private javax.swing.JTextField text_fec_nac_padre3;
    private javax.swing.JTextField text_lugar_nac_padre;
    private javax.swing.JTextField text_lugar_nac_padre1;
    private javax.swing.JTextField text_lugar_nac_padre2;
    private javax.swing.JTextField text_lugar_nac_padre3;
    private javax.swing.JTextField text_lugar_nac_padre4;
    private javax.swing.JTextField text_lugar_nac_padre5;
    private javax.swing.JTextField text_lugar_nac_padre6;
    private javax.swing.JTextField text_lugar_nac_padre7;
    private javax.swing.JTextField text_nombres_padre;
    private javax.swing.JTextField text_nombres_padre1;
    private javax.swing.JTextField text_nombres_padre2;
    private javax.swing.JTextField text_nombres_padre3;
    private javax.swing.JTextField text_nombres_padre4;
    private javax.swing.JTextField text_ocupacion_padre;
    private javax.swing.JTextField text_ocupacion_padre1;
    private javax.swing.JTextField text_ocupacion_padre2;
    private javax.swing.JTextField text_ocupacion_padre3;
    private javax.swing.JTextField text_ocupacion_padre4;
    private javax.swing.JTextField text_tlf_padre;
    private javax.swing.JTextField text_tlf_padre1;
    private javax.swing.JTextField text_tlf_padre2;
    private javax.swing.JTextField text_tlf_padre3;
    private javax.swing.JTextField text_tlf_padre4;
    private javax.swing.JTextField text_tlf_padre5;
    private javax.swing.JTextField text_tlf_padre6;
    private javax.swing.JTextField text_tlf_padre7;
    private javax.swing.JTextField text_tlf_padre8;
    private javax.swing.JTextField text_tlf_padre9;
    // End of variables declaration//GEN-END:variables
}
