/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

/**
 *
 * @author Admin
 */
public class menu_principal extends javax.swing.JFrame {

private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(menu_principal.class.getName());

/**
 * Creates new form Menu_Principal
 */
public menu_principal() {
    initComponents();
}

public void createConfPanel(){
    conf_frame conf_main = new conf_frame();
    conf_main.setVisible(true);
}

/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenu1 = new javax.swing.JMenu();
        btnReportes = new javax.swing.JButton();
        btnEstudiantes = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnEstudiantes1 = new javax.swing.JButton();
        btnEstudiantes2 = new javax.swing.JButton();
        btnEstudiantes4 = new javax.swing.JButton();
        btnEstudiantes5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu3.setText("jMenu3");

        jMenu1.setText("jMenu1");

        btnReportes.setBackground(new java.awt.Color(62, 181, 157));
        btnReportes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReportes.setForeground(new java.awt.Color(250, 247, 239));
        btnReportes.setText("Reportes");
        btnReportes.setIconTextGap(30);
        btnReportes.setMaximumSize(new java.awt.Dimension(100, 40));
        btnReportes.setMinimumSize(new java.awt.Dimension(100, 40));
        btnReportes.setPreferredSize(new java.awt.Dimension(160, 40));
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IM");
        setBackground(new java.awt.Color(197, 232, 225));
        setMinimumSize(new java.awt.Dimension(1280, 800));

        btnEstudiantes.setBackground(new java.awt.Color(62, 181, 157));
        btnEstudiantes.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        btnEstudiantes.setForeground(new java.awt.Color(250, 247, 239));
        btnEstudiantes.setText("Estudiantes");
        btnEstudiantes.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnEstudiantes.setIconTextGap(25);
        btnEstudiantes.setMaximumSize(new java.awt.Dimension(100, 40));
        btnEstudiantes.setMinimumSize(new java.awt.Dimension(250, 56));
        btnEstudiantes.setPreferredSize(new java.awt.Dimension(256, 56));
        btnEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstudiantesActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(27, 120, 101));

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 72)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(250, 247, 239));
        jLabel1.setText("Menu Principal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(417, 417, 417)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnEstudiantes1.setBackground(new java.awt.Color(62, 181, 157));
        btnEstudiantes1.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        btnEstudiantes1.setForeground(new java.awt.Color(250, 247, 239));
        btnEstudiantes1.setText("Representantes");
        btnEstudiantes1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnEstudiantes1.setIconTextGap(25);
        btnEstudiantes1.setMaximumSize(new java.awt.Dimension(100, 40));
        btnEstudiantes1.setMinimumSize(new java.awt.Dimension(250, 56));
        btnEstudiantes1.setPreferredSize(new java.awt.Dimension(250, 56));
        btnEstudiantes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstudiantes1ActionPerformed(evt);
            }
        });

        btnEstudiantes2.setBackground(new java.awt.Color(62, 181, 157));
        btnEstudiantes2.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        btnEstudiantes2.setForeground(new java.awt.Color(250, 247, 239));
        btnEstudiantes2.setText("Autorizados");
        btnEstudiantes2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnEstudiantes2.setIconTextGap(25);
        btnEstudiantes2.setMaximumSize(new java.awt.Dimension(100, 40));
        btnEstudiantes2.setMinimumSize(new java.awt.Dimension(250, 56));
        btnEstudiantes2.setPreferredSize(new java.awt.Dimension(250, 56));
        btnEstudiantes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstudiantes2ActionPerformed(evt);
            }
        });

        btnEstudiantes4.setBackground(new java.awt.Color(62, 181, 157));
        btnEstudiantes4.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        btnEstudiantes4.setForeground(new java.awt.Color(250, 247, 239));
        btnEstudiantes4.setText("Obreros");
        btnEstudiantes4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnEstudiantes4.setIconTextGap(25);
        btnEstudiantes4.setMaximumSize(new java.awt.Dimension(100, 40));
        btnEstudiantes4.setMinimumSize(new java.awt.Dimension(250, 56));
        btnEstudiantes4.setPreferredSize(new java.awt.Dimension(250, 56));
        btnEstudiantes4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstudiantes4ActionPerformed(evt);
            }
        });

        btnEstudiantes5.setBackground(new java.awt.Color(62, 181, 157));
        btnEstudiantes5.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        btnEstudiantes5.setForeground(new java.awt.Color(250, 247, 239));
        btnEstudiantes5.setText("Configuración");
        btnEstudiantes5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnEstudiantes5.setIconTextGap(25);
        btnEstudiantes5.setMaximumSize(new java.awt.Dimension(100, 40));
        btnEstudiantes5.setMinimumSize(new java.awt.Dimension(250, 56));
        btnEstudiantes5.setPreferredSize(new java.awt.Dimension(250, 56));
        btnEstudiantes5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstudiantes5ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 4)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/set2/talent_256.png"))); // NOI18N
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel5.setAlignmentY(0.0F);
        jLabel5.setAutoscrolls(true);
        jLabel5.setFocusable(false);
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel5.setIconTextGap(0);
        jLabel5.setRequestFocusEnabled(false);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 4)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/logo_inst_256.png"))); // NOI18N
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel6.setAlignmentY(0.0F);
        jLabel6.setAutoscrolls(true);
        jLabel6.setFocusable(false);
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel6.setIconTextGap(0);
        jLabel6.setRequestFocusEnabled(false);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 4)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/set2/kid_256.png"))); // NOI18N
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel7.setAlignmentY(0.0F);
        jLabel7.setAutoscrolls(true);
        jLabel7.setFocusable(false);
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel7.setIconTextGap(0);
        jLabel7.setRequestFocusEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(btnEstudiantes4, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEstudiantes5, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(226, 226, 226))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(204, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEstudiantes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEstudiantes2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(btnEstudiantes1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(185, 185, 185))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(546, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGap(534, 534, 534)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEstudiantes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEstudiantes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 276, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEstudiantes4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEstudiantes5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(489, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGap(55, 55, 55)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_btnReportesActionPerformed

    private void btnEstudiantes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstudiantes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEstudiantes1ActionPerformed

    private void btnEstudiantes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstudiantes2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEstudiantes2ActionPerformed

    private void btnEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstudiantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEstudiantesActionPerformed

    private void btnEstudiantes4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstudiantes4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEstudiantes4ActionPerformed

    private void btnEstudiantes5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstudiantes5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEstudiantes5ActionPerformed

private void MenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {

    System.exit(0); // Cierra la aplicación Java
}

private void menuItemConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {
    //ConfiguracionForm config = new ConfiguracionForm(); // Asume que creaste esta clase
    //config.setVisible(true);
    // Opcional: Si quieres cerrar el menú principal mientras la configuración está abierta
    // this.dispose(); // No siempre deseable para una ventana de configuración
}        // TODO add your handling code here:
        // GEN-LAST:event_MenuItemConfiguracionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new menu_principal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEstudiantes;
    private javax.swing.JButton btnEstudiantes1;
    private javax.swing.JButton btnEstudiantes2;
    private javax.swing.JButton btnEstudiantes4;
    private javax.swing.JButton btnEstudiantes5;
    private javax.swing.JButton btnReportes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables
}
