/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms;

public class menuReportes extends javax.swing.JDialog {
    
    public menuReportes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_vacio = new javax.swing.JPanel();
        panel_licenciaMedica = new javax.swing.JPanel();
        lbl_direcPerMed = new javax.swing.JLabel();
        txt_direcPerMed = new javax.swing.JTextField();
        panel_constRetiro = new javax.swing.JPanel();
        lbl_plantel = new javax.swing.JLabel();
        txt_plantel = new javax.swing.JTextField();
        lbl_municipio = new javax.swing.JLabel();
        txt_municipio = new javax.swing.JTextField();
        lbl_estado = new javax.swing.JLabel();
        txt_estado = new javax.swing.JTextField();
        lbl_distrito = new javax.swing.JLabel();
        txt_distrito = new javax.swing.JTextField();
        lbl_motivo = new javax.swing.JLabel();
        txt_motivo = new javax.swing.JTextField();
        lbl_dias = new javax.swing.JLabel();
        txt_dias = new javax.swing.JTextField();
        lbl_inicio = new javax.swing.JLabel();
        txt_inicio = new javax.swing.JTextField();
        lbl_fin = new javax.swing.JLabel();
        txt_fin = new javax.swing.JTextField();
        headder = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        cmb_tipoReporte = new javax.swing.JComboBox<>();
        btn_buscarReporte = new javax.swing.JButton();
        lbl_persReporte = new javax.swing.JLabel();
        txt_persReporte = new javax.swing.JTextField();
        lbl_ciPersReporte = new javax.swing.JLabel();
        txt_ciPersReporte = new javax.swing.JTextField();

        panel_vacio.setBackground(new java.awt.Color(197, 232, 225));

        javax.swing.GroupLayout panel_vacioLayout = new javax.swing.GroupLayout(panel_vacio);
        panel_vacio.setLayout(panel_vacioLayout);
        panel_vacioLayout.setHorizontalGroup(
            panel_vacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 656, Short.MAX_VALUE)
        );
        panel_vacioLayout.setVerticalGroup(
            panel_vacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
        );

        panel_licenciaMedica.setBackground(new java.awt.Color(197, 232, 225));

        lbl_direcPerMed.setText("Quien suscribe:");

        javax.swing.GroupLayout panel_licenciaMedicaLayout = new javax.swing.GroupLayout(panel_licenciaMedica);
        panel_licenciaMedica.setLayout(panel_licenciaMedicaLayout);
        panel_licenciaMedicaLayout.setHorizontalGroup(
            panel_licenciaMedicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_licenciaMedicaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_direcPerMed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_direcPerMed, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(430, Short.MAX_VALUE))
        );
        panel_licenciaMedicaLayout.setVerticalGroup(
            panel_licenciaMedicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_licenciaMedicaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_licenciaMedicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_direcPerMed)
                    .addComponent(txt_direcPerMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(254, Short.MAX_VALUE))
        );

        panel_constRetiro.setBackground(new java.awt.Color(204, 204, 255));

        lbl_plantel.setText("Plantel:");

        lbl_municipio.setText("Municipio");

        lbl_estado.setText("Estado");

        lbl_distrito.setText("Distrito");

        lbl_motivo.setText("Motivo");

        lbl_dias.setText("Cantidad de dias");

        lbl_inicio.setText("Dia inicio");

        lbl_fin.setText("Dia Fin");

        javax.swing.GroupLayout panel_constRetiroLayout = new javax.swing.GroupLayout(panel_constRetiro);
        panel_constRetiro.setLayout(panel_constRetiroLayout);
        panel_constRetiroLayout.setHorizontalGroup(
            panel_constRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_constRetiroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_constRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel_constRetiroLayout.createSequentialGroup()
                        .addComponent(lbl_plantel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_plantel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_constRetiroLayout.createSequentialGroup()
                        .addComponent(lbl_municipio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_municipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_constRetiroLayout.createSequentialGroup()
                        .addComponent(lbl_estado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_constRetiroLayout.createSequentialGroup()
                        .addComponent(lbl_distrito)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_distrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_constRetiroLayout.createSequentialGroup()
                        .addComponent(lbl_motivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_motivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_constRetiroLayout.createSequentialGroup()
                        .addComponent(lbl_fin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_fin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_constRetiroLayout.createSequentialGroup()
                        .addComponent(lbl_inicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_constRetiroLayout.createSequentialGroup()
                        .addComponent(lbl_dias)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_dias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(624, Short.MAX_VALUE))
        );
        panel_constRetiroLayout.setVerticalGroup(
            panel_constRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_constRetiroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_constRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_plantel)
                    .addComponent(txt_plantel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_constRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_municipio)
                    .addComponent(txt_municipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_constRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_estado)
                    .addComponent(txt_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_constRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_distrito)
                    .addComponent(txt_distrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_constRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_motivo)
                    .addComponent(txt_motivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_constRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_dias)
                    .addComponent(txt_dias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_constRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_inicio)
                    .addComponent(txt_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_constRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_fin)
                    .addComponent(txt_fin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(241, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        headder.setBackground(new java.awt.Color(27, 120, 101));
        headder.setPreferredSize(new java.awt.Dimension(668, 48));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(250, 247, 239));
        jLabel1.setText("Reportes");

        javax.swing.GroupLayout headderLayout = new javax.swing.GroupLayout(headder);
        headder.setLayout(headderLayout);
        headderLayout.setHorizontalGroup(
            headderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headderLayout.createSequentialGroup()
                .addContainerGap(326, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(324, 324, 324))
        );
        headderLayout.setVerticalGroup(
            headderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headderLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panel.setBackground(new java.awt.Color(197, 232, 225));
        panel.setLayout(new java.awt.CardLayout());

        cmb_tipoReporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Permiso Medico", "Constancia de retiro", "Constacia de conducta", "Constacia de estudios", " ", " " }));
        cmb_tipoReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_tipoReporteActionPerformed(evt);
            }
        });

        btn_buscarReporte.setText("Generar");
        btn_buscarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarReporteActionPerformed(evt);
            }
        });

        lbl_persReporte.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbl_persReporte.setText("Nombre:");

        txt_persReporte.setEditable(false);
        txt_persReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_persReporteActionPerformed(evt);
            }
        });

        lbl_ciPersReporte.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbl_ciPersReporte.setText("Cédula:");

        txt_ciPersReporte.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headder, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmb_tipoReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_buscarReporte)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_persReporte)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_persReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_ciPersReporte)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_ciPersReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_ciPersReporte)
                        .addComponent(txt_ciPersReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmb_tipoReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_persReporte)
                        .addComponent(txt_persReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_buscarReporte)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void cmb_tipoReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_tipoReporteActionPerformed

    }//GEN-LAST:event_cmb_tipoReporteActionPerformed

    private void btn_buscarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarReporteActionPerformed
        if (cmb_tipoReporte.getSelectedItem() == "..."){
            panel.removeAll();
            panel.add(panel_vacio);
            panel.repaint();
            panel.revalidate();
        }
        if (cmb_tipoReporte.getSelectedItem() == "Permiso Medico"){
            panel.removeAll();
            panel.add(panel_licenciaMedica);
            panel.repaint();
            panel.revalidate();
        }
        if (cmb_tipoReporte.getSelectedItem() == "Constancia de estudios"){
            panel.removeAll();
            panel.add(panel_licenciaMedica);
            panel.repaint();
            panel.revalidate();
        }
        if (cmb_tipoReporte.getSelectedItem() == "Constancia de conducta"){
            panel.removeAll();
            panel.add(panel_licenciaMedica);
            panel.repaint();
            panel.revalidate();
        }
        if (cmb_tipoReporte.getSelectedItem() == "Constancia de retiro"){
            panel.removeAll();
            panel.add(panel_licenciaMedica);
            panel.repaint();
            panel.revalidate();
        }
        
    }//GEN-LAST:event_btn_buscarReporteActionPerformed

    private void txt_persReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_persReporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_persReporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                menuReportes dialog = new menuReportes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscarReporte;
    private javax.swing.JComboBox<String> cmb_tipoReporte;
    private javax.swing.JPanel headder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_ciPersReporte;
    private javax.swing.JLabel lbl_dias;
    private javax.swing.JLabel lbl_direcPerMed;
    private javax.swing.JLabel lbl_distrito;
    private javax.swing.JLabel lbl_estado;
    private javax.swing.JLabel lbl_fin;
    private javax.swing.JLabel lbl_inicio;
    private javax.swing.JLabel lbl_motivo;
    private javax.swing.JLabel lbl_municipio;
    private javax.swing.JLabel lbl_persReporte;
    private javax.swing.JLabel lbl_plantel;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panel_constRetiro;
    private javax.swing.JPanel panel_licenciaMedica;
    private javax.swing.JPanel panel_vacio;
    private javax.swing.JTextField txt_ciPersReporte;
    private javax.swing.JTextField txt_dias;
    private javax.swing.JTextField txt_direcPerMed;
    private javax.swing.JTextField txt_distrito;
    private javax.swing.JTextField txt_estado;
    private javax.swing.JTextField txt_fin;
    private javax.swing.JTextField txt_inicio;
    private javax.swing.JTextField txt_motivo;
    private javax.swing.JTextField txt_municipio;
    private javax.swing.JTextField txt_persReporte;
    private javax.swing.JTextField txt_plantel;
    // End of variables declaration//GEN-END:variables
}
