/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

/**
 *
 * @author Admin
 */
public class menu_principal extends javax.swing.JFrame {

    public conf_frame conf = null;
    public busqueda_estudiante estudiante = null;
    public busqueda_representante representante = null;
    public busqueda_obrero obrero = null;
    
    
private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(menu_principal.class.getName());

/**
 * Creates new form Menu_Principal
 */
public menu_principal() {
    initComponents();
    
}

public void createConfPanel(){
    conf_frame conf_main = new conf_frame();
    conf_main.setVisible(true);
}

/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headder = new javax.swing.JPanel();
        txtMenuPrincipal = new javax.swing.JLabel();
        imgEstudiante = new javax.swing.JLabel();
        btnEstudiantes = new javax.swing.JButton();
        imgFamilia = new javax.swing.JLabel();
        btnRepresentantes = new javax.swing.JButton();
        imgAutorizado = new javax.swing.JLabel();
        btnAutorizados = new javax.swing.JButton();
        imgMaletin = new javax.swing.JLabel();
        btnPlantel = new javax.swing.JButton();
        imgHerramienta = new javax.swing.JLabel();
        btnConfiguracion = new javax.swing.JButton();
        logoPreescolar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IM");
        setBackground(new java.awt.Color(197, 232, 225));
        setMinimumSize(new java.awt.Dimension(1280, 800));

        headder.setBackground(new java.awt.Color(27, 120, 101));

        txtMenuPrincipal.setBackground(new java.awt.Color(204, 204, 255));
        txtMenuPrincipal.setFont(new java.awt.Font("Segoe UI", 1, 72)); // NOI18N
        txtMenuPrincipal.setForeground(new java.awt.Color(250, 247, 239));
        txtMenuPrincipal.setText("Menu Principal");

        javax.swing.GroupLayout headderLayout = new javax.swing.GroupLayout(headder);
        headder.setLayout(headderLayout);
        headderLayout.setHorizontalGroup(
            headderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headderLayout.createSequentialGroup()
                .addGap(417, 417, 417)
                .addComponent(txtMenuPrincipal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headderLayout.setVerticalGroup(
            headderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtMenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        imgEstudiante.setFont(new java.awt.Font("Segoe UI", 0, 4)); // NOI18N
        imgEstudiante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/set2/kid_256.png"))); // NOI18N
        imgEstudiante.setToolTipText("");
        imgEstudiante.setAlignmentY(0.0F);
        imgEstudiante.setAutoscrolls(true);
        imgEstudiante.setFocusable(false);
        imgEstudiante.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        imgEstudiante.setIconTextGap(0);
        imgEstudiante.setRequestFocusEnabled(false);

        btnEstudiantes.setBackground(new java.awt.Color(62, 181, 157));
        btnEstudiantes.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        btnEstudiantes.setForeground(new java.awt.Color(250, 247, 239));
        btnEstudiantes.setText("ESTUDIANTES");
        btnEstudiantes.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnEstudiantes.setIconTextGap(25);
        btnEstudiantes.setMaximumSize(new java.awt.Dimension(100, 40));
        btnEstudiantes.setMinimumSize(new java.awt.Dimension(250, 56));
        btnEstudiantes.setPreferredSize(new java.awt.Dimension(256, 56));
        btnEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstudiantesActionPerformed(evt);
            }
        });

        imgFamilia.setFont(new java.awt.Font("Segoe UI", 0, 4)); // NOI18N
        imgFamilia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgFamilia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/set2/family_256.png"))); // NOI18N
        imgFamilia.setAlignmentY(0.0F);
        imgFamilia.setAutoscrolls(true);
        imgFamilia.setFocusable(false);
        imgFamilia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        imgFamilia.setIconTextGap(0);
        imgFamilia.setRequestFocusEnabled(false);

        btnRepresentantes.setBackground(new java.awt.Color(62, 181, 157));
        btnRepresentantes.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        btnRepresentantes.setForeground(new java.awt.Color(250, 247, 239));
        btnRepresentantes.setText("REPRESENTANTES");
        btnRepresentantes.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnRepresentantes.setIconTextGap(25);
        btnRepresentantes.setMaximumSize(new java.awt.Dimension(100, 40));
        btnRepresentantes.setMinimumSize(new java.awt.Dimension(250, 56));
        btnRepresentantes.setPreferredSize(new java.awt.Dimension(250, 56));
        btnRepresentantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepresentantesActionPerformed(evt);
            }
        });

        imgAutorizado.setFont(new java.awt.Font("Segoe UI", 0, 4)); // NOI18N
        imgAutorizado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgAutorizado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/set2/talent_256.png"))); // NOI18N
        imgAutorizado.setAlignmentY(0.0F);
        imgAutorizado.setAutoscrolls(true);
        imgAutorizado.setFocusable(false);
        imgAutorizado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        imgAutorizado.setIconTextGap(0);
        imgAutorizado.setRequestFocusEnabled(false);

        btnAutorizados.setBackground(new java.awt.Color(62, 181, 157));
        btnAutorizados.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        btnAutorizados.setForeground(new java.awt.Color(250, 247, 239));
        btnAutorizados.setText("AUTORIZADOS");
        btnAutorizados.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAutorizados.setIconTextGap(25);
        btnAutorizados.setMaximumSize(new java.awt.Dimension(100, 40));
        btnAutorizados.setMinimumSize(new java.awt.Dimension(250, 56));
        btnAutorizados.setPreferredSize(new java.awt.Dimension(250, 56));
        btnAutorizados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutorizadosActionPerformed(evt);
            }
        });

        imgMaletin.setFont(new java.awt.Font("Segoe UI", 0, 4)); // NOI18N
        imgMaletin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgMaletin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/set2/suitcase_256.png"))); // NOI18N
        imgMaletin.setToolTipText("");
        imgMaletin.setAlignmentY(0.0F);
        imgMaletin.setAutoscrolls(true);
        imgMaletin.setFocusable(false);
        imgMaletin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        imgMaletin.setIconTextGap(0);
        imgMaletin.setRequestFocusEnabled(false);

        btnPlantel.setBackground(new java.awt.Color(62, 181, 157));
        btnPlantel.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        btnPlantel.setForeground(new java.awt.Color(250, 247, 239));
        btnPlantel.setText("PLANTEL");
        btnPlantel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPlantel.setIconTextGap(25);
        btnPlantel.setMaximumSize(new java.awt.Dimension(100, 40));
        btnPlantel.setMinimumSize(new java.awt.Dimension(250, 56));
        btnPlantel.setPreferredSize(new java.awt.Dimension(250, 56));
        btnPlantel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlantelActionPerformed(evt);
            }
        });

        imgHerramienta.setFont(new java.awt.Font("Segoe UI", 0, 4)); // NOI18N
        imgHerramienta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgHerramienta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/set1/tools_240.png"))); // NOI18N
        imgHerramienta.setAlignmentY(0.0F);
        imgHerramienta.setAutoscrolls(true);
        imgHerramienta.setFocusable(false);
        imgHerramienta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        imgHerramienta.setIconTextGap(0);
        imgHerramienta.setRequestFocusEnabled(false);

        btnConfiguracion.setBackground(new java.awt.Color(62, 181, 157));
        btnConfiguracion.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        btnConfiguracion.setForeground(new java.awt.Color(250, 247, 239));
        btnConfiguracion.setText("CONFIG");
        btnConfiguracion.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnConfiguracion.setIconTextGap(25);
        btnConfiguracion.setMaximumSize(new java.awt.Dimension(100, 40));
        btnConfiguracion.setMinimumSize(new java.awt.Dimension(250, 56));
        btnConfiguracion.setPreferredSize(new java.awt.Dimension(250, 56));
        btnConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfiguracionActionPerformed(evt);
            }
        });

        logoPreescolar.setFont(new java.awt.Font("Segoe UI", 0, 4)); // NOI18N
        logoPreescolar.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        logoPreescolar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/logo_inst_256.png"))); // NOI18N
        logoPreescolar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        logoPreescolar.setAlignmentY(0.0F);
        logoPreescolar.setAutoscrolls(true);
        logoPreescolar.setFocusable(false);
        logoPreescolar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logoPreescolar.setIconTextGap(0);
        logoPreescolar.setRequestFocusEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(204, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imgMaletin)
                    .addComponent(btnPlantel, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imgEstudiante))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRepresentantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(imgFamilia, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAutorizados, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imgAutorizado)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(427, 427, 427)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnConfiguracion, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(imgHerramienta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(185, 185, 185))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(546, Short.MAX_VALUE)
                    .addComponent(logoPreescolar)
                    .addGap(534, 534, 534)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(headder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(imgEstudiante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(imgFamilia)
                            .addComponent(imgAutorizado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRepresentantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAutorizados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(imgMaletin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imgHerramienta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPlantel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(489, Short.MAX_VALUE)
                    .addComponent(logoPreescolar)
                    .addGap(55, 55, 55)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAutorizadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutorizadosActionPerformed
        if (representante == null) {
            representante = new busqueda_representante();
        } else {
        representante.dispose();
        representante.setVisible(true);
        }
        representante.setAlwaysOnTop(rootPaneCheckingEnabled);
        representante.setLocationRelativeTo(null);
        representante.setVisible(true);
    }//GEN-LAST:event_btnAutorizadosActionPerformed

    private void btnRepresentantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepresentantesActionPerformed
        if (representante == null) {
            representante = new busqueda_representante();
        } else {
        representante.dispose();
        representante.setVisible(true);
        }
        representante.setAlwaysOnTop(rootPaneCheckingEnabled);
        representante.setLocationRelativeTo(null);
        representante.setVisible(true);
    }//GEN-LAST:event_btnRepresentantesActionPerformed

    private void btnEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstudiantesActionPerformed
        if (estudiante == null) {
            estudiante = new busqueda_estudiante();
        } else {
        estudiante.dispose();
        estudiante.setVisible(true);
        }
        estudiante.setAlwaysOnTop(rootPaneCheckingEnabled);
        estudiante.setLocationRelativeTo(null);
        estudiante.setVisible(true);
    }//GEN-LAST:event_btnEstudiantesActionPerformed

    private void btnPlantelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlantelActionPerformed
        if (obrero == null) {
            obrero = new busqueda_obrero();
        } else {
        obrero.dispose();
        obrero.setVisible(true);
        }
        obrero.setAlwaysOnTop(rootPaneCheckingEnabled);
        obrero.setLocationRelativeTo(null);
        obrero.setVisible(true);
    }//GEN-LAST:event_btnPlantelActionPerformed

    private void btnConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfiguracionActionPerformed

        if (conf == null){
            conf = new conf_frame();
        } else {
        conf.dispose();
        conf.setVisible(true);
        }
        conf.setAlwaysOnTop(rootPaneCheckingEnabled);
        conf.setLocationRelativeTo(null);
        conf.setVisible(true);
    }//GEN-LAST:event_btnConfiguracionActionPerformed

private void MenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {

    System.exit(0); // Cierra la aplicación Java
}

private void menuItemConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {
    //ConfiguracionForm config = new ConfiguracionForm(); // Asume que creaste esta clase
    //config.setVisible(true);
    // Opcional: Si quieres cerrar el menú principal mientras la configuración está abierta
    // this.dispose(); // No siempre deseable para una ventana de configuración
}        // TODO add your handling code here:
        // GEN-LAST:event_MenuItemConfiguracionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new menu_principal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutorizados;
    private javax.swing.JButton btnConfiguracion;
    private javax.swing.JButton btnEstudiantes;
    private javax.swing.JButton btnPlantel;
    private javax.swing.JButton btnRepresentantes;
    private javax.swing.JPanel headder;
    private javax.swing.JLabel imgAutorizado;
    private javax.swing.JLabel imgEstudiante;
    private javax.swing.JLabel imgFamilia;
    private javax.swing.JLabel imgHerramienta;
    private javax.swing.JLabel imgMaletin;
    private javax.swing.JLabel logoPreescolar;
    private javax.swing.JLabel txtMenuPrincipal;
    // End of variables declaration//GEN-END:variables
}
